markdown: kramdown
paginate: 5
paginate_path: "/:num/"
title: "itinerantfoodie :: eat, sleep, and travel"
description: "itinerantfoodie is a travel / food / lifestyle blog"
url: "http://www.nolim1t.co"
author: "@nolim1t"
gems:
  - jekyll-paginate
  - jekyll-feed
