markdown: kramdown
permalink: /post/:categories/:year-:month-:day/:slug.html
paginate: 5
paginate_path: "/:num/"
title: "itinerantfoodie :: eat, sleep, and travel"
description: "itinerantfoodie is a travel / food / lifestyle blog"
url: "https://itinerantfoodie.com"
author: "@nolim1t"
feed:
  path: /rss/index.html
gems:
  - jekyll-paginate
  - jekyll-feed
